// Generated by CoffeeScript 2.3.0
(function() {
  gg.Inventory = class Inventory {
    constructor() {
      this.items = {};
      this.it = null;
      this.using = null;
      this.object = null;
      this.sel = null;
      this.inventory = $('<div id="inventory">');
      $('#overlay').append(this.inventory);
      this.build();
    }

    dtor() {
      return this.inventory.remove();
    }

    patch(items) {
      this.items = items;
      this.build();
      return true;
    }

    build() {
      var e, inv, k, n, ref, v;
      inv = this;
      this.stuff = $('<div class="in">');
      ref = this.items;
      for (k in ref) {
        v = ref[k];
        e = $("<div class=\"item\">");
        e.append(`<span class="name">${k}</span>`);
        if (k === this.using) {
          e.addClass('it');
          inv.it = e;
        }
        e.click(function() {
          var accuracy, bar, damage, firerate, image, j, mix, range, recoil, stat, stats, wep;
          j = $(this);
          if (inv.it === j) {
            return;
          }
          if (inv.it != null) {
            inv.it.removeClass('it');
          }
          j.addClass('it');
          inv.using = j.children()[0].innerHTML;
          inv.it = j;
          gg.ply.hold(gg.weps[inv.using] || null);
          gg.net.out.SEL = inv.using;
          wep = gg.weps[inv.using];
          if (wep != null) {
            $('#gun').empty();
            image = $(`<img src="play/sty/nontile/mcitems/${wep.sty}.png"></img>`);
            stats = $('<div class="stats">');
            //stat = $ "<div class=\"stat\">"
            //stat.append "<div class=\"name\">Damage:</div>"
            //stat.append "<div class=\"bar\"><div class=\"value\">#{wep.damage}</div></div>"
            //stats.append stat
            if (wep.damage != null) {
              damage = Math.floor(wep.damage / 100 * 100);
              bar = Math.min(damage, 100).toFixed(0);
              stat = $("<div class=\"stat\">");
              stat.append("<div class=\"name\">Damage/</div>");
              stat.append(`<div class="bar percent"> <div class="value" style="width: ${bar}%">${damage}</div> </div> <div class="end"></div>`);
              stats.append(stat);
            }
            if (wep.accuracy != null) {
              accuracy = Math.floor(wep.accuracy * 100);
              bar = Math.min(accuracy, 100).toFixed(0);
              mix = $('<div style="line-height: 0;">');
              stat = $("<div class=\"stat\" style=\"width: 50%; display: inline-block;\">");
              stat.append("<div class=\"name\">Accuracy/</div>");
              stat.append(`<div class="bar percent"> <div class="value" style="width: ${bar}%">${accuracy}</div> </div> <div class="end"></div>`);
              mix.append(stat);
              recoil = Math.floor(wep.recoil * 100);
              bar = Math.min(recoil, 100).toFixed(0);
              stat = $("<div class=\"stat\" style=\"width: 50%; display: inline-block;\">");
              stat.append("<div class=\"name\" style=\"padding-left: 2ex;\">Recoil/</div>");
              stat.append(`<div class="bar percent"> <div class="value" style="width: ${bar}%">${recoil}</div> </div> <div class="end"></div>`);
              mix.append(stat);
              stats.append(mix);
            }
            if (wep.range != null) {
              range = Math.floor(wep.range * 100);
              bar = Math.min(range, 100).toFixed(0);
              stat = $("<div class=\"stat\">");
              stat.append("<div class=\"name\">Range/</div>");
              stat.append(`<div class="bar percent"> <div class="value" style="width: ${bar}%">${range}</div> </div> <div class="end"></div>`);
              stats.append(stat);
            }
            if (wep.firerate) {
              firerate = (wep.firerate / 20) * 100;
              bar = Math.min(firerate, 100).toFixed(0);
              stat = $("<div class=\"stat\">");
              stat.append("<div class=\"name\">Firerate/</div>");
              stat.append(`<div class="bar percent"> <div class="value" style="width: ${bar}%">${wep.firerate}</div> </div> <div class="end"></div>`);
              stats.append(stat);
            }
            $('#gun').append(image);
            $('#gun').append(stats);
          } else {
            $('#gun').html('');
          }
          return true;
        });
        n = v > 1 ? v : '&nbsp';
        e.append(`<span class="count">${n}</span>`);
        this.stuff.append(e);
      }
      this.inventory.html(this.stuff);
      return true;
    }

  };

}).call(this);
