// Generated by CoffeeScript 2.3.0
(function() {
  gg.Sound = class Sound extends gg.Entity {
    constructor(props) {
      var that;
      super(props);
      that = this;
      this.shape();
      this.pose();
    }

    build() {
      // gg.scene.add @audio
      return 1;
    }

    dtor() {
      // gg.scene.remove @audio
      return 1;
    }

    shape() {
      // that.audio.setBuffer buffer
      // that.audio.setRefDistance that.data.refDistance or 4
      // that.audio.setLoop that.data.loop###
      return 1;
    }

    pose() {
      // @audio.position.set @props.x, @data.y, @data.z
      return 1;
    }

    step() {
      this.pose();
      return 1;
    }

  };

}).call(this);
