// Generated by CoffeeScript 1.9.3
(function() {
  gg.Visual = (function() {
    function Visual(props) {
      this.props = props;
      this.type = 'Untyped';
    }

    Visual.prototype.dtor = function() {
      return 0;
    };

    Visual.prototype.step = function() {
      return 0;
    };

    Visual.prototype.patch = function() {
      return 0;
    };

    Visual.prototype.show = function() {
      return 0;
    };

    return Visual;

  })();

}).call(this);
