// Generated by CoffeeScript 1.10.0
(function() {
  var armory, go, popoff, popup, root, types;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  armory = {
    weps: null,
    path: '../play/sty/nontile/mcitems/',
    types: {},
    nondescript: true
  };

  $(document).ready(function() {
    $('body').append($('<div class="armory">'));
    $('body').append($('<div class="descriptor">'));
    $.getJSON('../sons/weps.json', function(data) {
      armory.weps = data;
      types.call(armory);
      go.call(armory);
    });
    return 1;
  });

  $(document).mousemove(function(e) {
    var descriptor;
    if (armory.nondescript) {
      return;
    }
    descriptor = $('.descriptor');
    descriptor.css('top', e.pageY + 10);
    descriptor.css('left', e.pageX + 10);
  });

  types = function() {
    var a, base1, k, name, ref, ref1, type, v;
    ref = this.weps;
    for (k in ref) {
      v = ref[k];
      a = (base1 = this.types)[name = v.type] != null ? base1[name] : base1[name] = [];
      a.push(v);
    }
    types = $('<div class="types">');
    ref1 = this.types;
    for (k in ref1) {
      v = ref1[k];
      type = $("<div data-type=\"" + k + "\" class=\"type\">");
      types.append(type);
    }
    return $('.armory').append(types);
  };

  go = function() {
    var base, k, ref, v;
    ref = this.weps;
    for (k in ref) {
      v = ref[k];
      if (v.unlisted) {
        continue;
      }
      base = $("<div class=\"wep\">");
      base.wep = v;
      base.data('wep', v);
      base.css('background-image', "url(" + this.path + v.sty + ".png)");
      base.append($("<div class=\"stat\">" + k + " [" + v.type + "]</div>"));
      base.append($("<div class=\"stat\">market value: <span class=\"marketvalue\">$" + v.value + "</span></div>"));
      base.append($("<div class=\"stat\">magazine: " + v.magazine + "</div>"));
      base.append($("<div class=\"stat\">damage: " + v.damage + "</div>"));
      base.append($("<div class=\"stat\">accuracy: " + v.accuracy + "</div>"));
      base.append($("<div class=\"stat\">recoil: " + v.recoil + "</div>"));
      base.append($("<div class=\"stat\">range: " + v.range + "</div>"));
      base.append($("<div class=\"stat\">firerate: " + ((10 / v.firerate).toFixed(2)) + "Hz</div>"));
      $("*[data-type=\"" + v.type + "\"]").append(base);
      base.mouseenter(popup);
      base.mouseleave(popoff);
    }
    return 1;
  };

  popup = function(e) {
    var descriptor, that, wep;
    that = $(this);
    wep = that.data('wep');
    if (!wep.description) {
      return;
    }
    descriptor = $('.descriptor');
    descriptor.css('display', '');
    descriptor.html(wep.description);
    armory.nondescript = false;
    return 1;
  };

  popoff = function() {
    var descriptor, that;
    that = $(this);
    descriptor = $('.descriptor');
    descriptor.css('display', 'none');
    armory.nondescript = true;
    return 1;
  };

  root.armory = armory;

}).call(this);
