// Generated by CoffeeScript 2.3.0
(function() {
  var Account;

  Account = (function() {
    class Account {
      constructor(ses) {
        this.ses = ses;
      }

      fetch() {
        var query, that;
        query = `SELECT * FROM \`accounts\` WHERE x >= ${this.ux} AND y >= ${this.uy} AND x < ${this.uex} AND y < ${this.uey}`;
        that = this;
        gta.db.query(query, function(err, rows) {
          that.take(rows);
        });
        return 0;
      }

      take(param) {
        this.data = 0;
        return true;
      }

    };

    Account.static = false;

    return Account;

  }).call(this);

  module.exports = Account;

}).call(this);
